#!/bin/bash

# CMS Quick Start Guide
# This file contains the steps to get the CMS running

echo "==========================================="
echo "  CMS - Full Stack Content Management System"
echo "==========================================="
echo ""
echo "📋 QUICK START CHECKLIST"
echo ""
echo "✅ STEP 1: Install PostgreSQL"
echo "   - Read: POSTGRESQL_SETUP.md"
echo "   - Install PostgreSQL (v12 or higher)"
echo "   - Remember your postgres password"
echo ""
echo "✅ STEP 2: Backend Setup"
echo "   $ cd backend"
echo "   $ npm install"
echo ""
echo "✅ STEP 3: Configure Database"
echo "   $ cp .env.example .env"
echo "   - Edit .env with your PostgreSQL credentials"
echo ""
echo "✅ STEP 4: Initialize Database"
echo "   $ npm run setup-db"
echo "   - This creates database, user, tables, and indexes"
echo ""
echo "✅ STEP 5: Start Backend"
echo "   $ npm start"
echo "   - Should see: 'CMS Backend running on http://localhost:5000'"
echo ""
echo "✅ STEP 6: Frontend Setup (in new terminal)"
echo "   $ cd frontend"
echo "   $ npm install"
echo "   $ npm start"
echo "   - Browser will open to http://localhost:3000"
echo ""
echo "==========================================="
echo ""
echo "🎯 FIRST TIME USAGE"
echo ""
echo "1. Go to http://localhost:3000/register"
echo "2. Create your account"
echo "3. Log in"
echo "4. Go to Dashboard"
echo "5. Create your first post!"
echo ""
echo "==========================================="
echo ""
echo "📚 DOCUMENTATION"
echo ""
echo "Main Docs:       README.md"
echo "PostgreSQL:      POSTGRESQL_SETUP.md"
echo "Backend Server:  backend/server.js"
echo "Database Config: backend/db.js"
echo ""
echo "==========================================="
echo ""
echo "🔍 VERIFY EVERYTHING IS WORKING"
echo ""
echo "Backend Health Check:"
echo "  curl http://localhost:5000/api/health"
echo ""
echo "Frontend:"
echo "  http://localhost:3000"
echo ""
echo "==========================================="
